name: Continuous Integration Pipeline with SonarQube

on:
 workflow_dispatch

# Define permissions for the workflow
permissions:
 contents: read
 actions: read
 checks: write
 pull-requests: write

jobs:
 build-and-test:
   runs-on: ubuntu-latest
   environment: dev  

   steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 18.x
         cache: 'npm'
         cache-dependency-path: 'package-lock.json'

     - name: Install dependencies
       run: npm ci
       
     - name: Build the application (optional)
       run: |
         npm run build 2>/dev/null || echo "No build script found, skipping build step"
     
     - name: Install jest-junit
       run:  npm i --save-dev jest-junit
     - name: Run unit tests with coverage and JUnit reports
       run: |
        JEST_JUNIT_OUTPUT_DIR=coverage \
        JEST_JUNIT_OUTPUT_NAME=junit.xml \
        npm run test:coverage -- --reporters=jest-junit

     - name: Publish test results to Checks
       uses: dorny/test-reporter@v1
       if: always()
       with:
         name: Jest Test Results
         path: coverage/junit.xml
         reporter: jest-junit
         fail-on-error: true

     - name: Upload test results to GitHub
       uses: actions/upload-artifact@v4
       if: always()
       with:
         name: test-results-node
         path: coverage/
         retention-days: 30

     - name: SonarQube Scan
       uses: SonarSource/sonarqube-scan-action@v6.0.0
       env:
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       with:
         args: >
           -Dsonar.projectKey=sample-node-app-saurabh
           -Dsonar.organization=sda
           -Dsonar.token=${{ secrets.SONAR_TOKEN }}
           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
           -Dsonar.sources=.
           -Dsonar.exclusions=node_modules/**,coverage/**,tests/**,**/*.test.js,**/*.spec.js
           -Dsonar.tests=tests/
           -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js
           -Dsonar.coverage.exclusions=node_modules/**,coverage/**,tests/**,**/*.test.js,**/*.spec.js

     - name: Create deployment package
       run: |
         set -euo pipefail
         STAGING="$GITHUB_WORKSPACE/deployment-package"
         rm -rf "$STAGING"
         mkdir -p "$STAGING"

         [ -d public ] && cp -r public "$STAGING/" || echo "No public/ directory found"
         [ -d node_modules ] && cp -r node_modules "$STAGING/" || echo "No node_modules/ directory found"
         [ -f server.js ] && cp server.js "$STAGING/" || echo "No server.js found"
         cp package.json "$STAGING/"
         cp package-lock.json "$STAGING/"
         [ -f README.md ] && cp README.md "$STAGING/" || true
         [ -f Dockerfile ] && cp Dockerfile "$STAGING/" || echo "No Dockerfile found"

         (cd "$STAGING" && npm pkg delete devDependencies || true)

         TS="$(date +%Y%m%d-%H%M%S)"
         SHORT_SHA="${GITHUB_SHA::7}"
         ZIP_NAME="deployment-package-${SHORT_SHA}-${TS}.zip"
         (cd "$GITHUB_WORKSPACE" && zip -r "$ZIP_NAME" "deployment-package")
         echo "ZIP_NAME=$ZIP_NAME" >> "$GITHUB_ENV"

     - name: Upload deployment package artifact
       uses: actions/upload-artifact@v4
       with:
         name: deployment-package-node-${{ github.run_number }}
         path: ${{ env.ZIP_NAME }}
         retention-days: 90

